// PDF export utility using jsPDF + html2canvas

import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export async function exportToPDF(
  elementId: string,
  filename: string = "notER-report.pdf"
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element with id "${elementId}" not found`);
    return;
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: "#ffffff",
      logging: false,
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 10;
    const usableWidth = pageWidth - 2 * margin;

    const imgWidth = usableWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = margin;

    // First page
    pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - 2 * margin;

    // Additional pages if content overflows
    while (heightLeft > 0) {
      position = -(pageHeight - 2 * margin - heightLeft + margin);
      pdf.addPage();
      pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
      heightLeft -= pageHeight - 2 * margin;
    }

    pdf.save(filename);
  } catch (error) {
    console.error("PDF export failed:", error);
    throw error;
  }
}

export function printPrescription(elementId: string): void {
  const element = document.getElementById(elementId);
  if (!element) return;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Prescription — notER</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        
        * { box-sizing: border-box; margin: 0; padding: 0; }
        
        body {
          font-family: 'Inter', sans-serif;
          padding: 20mm;
          color: #1a1a1a;
          max-width: 210mm;
          margin: 0 auto;
        }
        
        .rx-header {
          text-align: center;
          border-bottom: 3px double #1E40AF;
          padding-bottom: 16px;
          margin-bottom: 16px;
        }
        
        .rx-header h1 {
          font-size: 22px;
          color: #1E40AF;
          margin-bottom: 4px;
        }
        
        .rx-header p {
          font-size: 12px;
          color: #666;
        }
        
        .rx-patient {
          display: flex;
          justify-content: space-between;
          padding: 12px 0;
          border-bottom: 1px solid #ddd;
          margin-bottom: 16px;
          font-size: 14px;
        }
        
        .rx-symbol {
          font-family: serif;
          font-size: 32px;
          font-weight: bold;
          color: #1E40AF;
          margin-bottom: 12px;
        }
        
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 8px;
        }
        
        th {
          background: #f0f4ff;
          padding: 10px 12px;
          text-align: left;
          font-size: 11px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          border-bottom: 2px solid #1E40AF;
          color: #333;
        }
        
        td {
          padding: 10px 12px;
          border-bottom: 1px solid #eee;
          font-size: 14px;
        }
        
        td:first-child {
          font-weight: 600;
          color: #1E40AF;
        }
        
        .rx-footer {
          margin-top: 40px;
          display: flex;
          justify-content: space-between;
          border-top: 1px solid #ddd;
          padding-top: 20px;
        }
        
        .rx-signature {
          text-align: right;
        }
        
        .rx-signature-line {
          width: 200px;
          border-top: 1px solid #333;
          margin-top: 40px;
          padding-top: 8px;
          font-size: 12px;
          color: #666;
        }
        
        @media print {
          body { padding: 15mm; }
        }
      </style>
    </head>
    <body>
      ${element.innerHTML}
      <div class="rx-footer">
        <div>
          <p style="font-size:11px;color:#999;">Generated by notER — AI Clinical Copilot</p>
        </div>
        <div class="rx-signature">
          <div class="rx-signature-line">Doctor's Signature</div>
        </div>
      </div>
      <script>
        window.onload = function() { window.print(); window.close(); }
      <\/script>
    </body>
    </html>
  `);

  printWindow.document.close();
}
